### PR TITLE
feat(srm) update SRM to handle BSSH events from orcabus ICAv2 event pipe

### PR DESCRIPTION
**Pull request by raylrui**
## SRM to handle BSSH events from orcabus ICAv2 event pipe

resolve https://github.com/umccr/orcabus/issues/696
1. add 'SequenceRunManagerStackEventRule" for filter BSSH event from ICAv2 event from event pipe
2. transfer from SQS 'sqs_handler' to orcabus 'event_handler'

image

SRM will take events with rule 
example event:
```
{
    "version": "0",
    "id": f8c3de3d-1fea-4d7c-a8b0-29f63c4c3454",  # Random UUID
    "detail-type": "Event from aws:sqs",
    "source": "Pipe IcaEventPipeConstru-xxxxxxxx",
    "account": "444444444444",
    "time": "2024-11-02T21:58:22Z",
    "region": "ap-southeast-2",
    "resources": [],
    "detail": {
        "ica-event": {
            "gdsFolderPath": "",
            "gdsVolumeName": "bssh.123456789fabcdefghijkl",
            "v1pre3Id": "444555555555",
            "dateModified": "2024-11-02T21:58:13.7451620Z",
            "acl": [
                "wid:12345678-debe-3f9f-8b92-21244f46822c",
                "tid:Yxmm......"
            ],
            "flowcellBarcode": "HVJJJJJJ",
            "icaProjectId": "12345678-53ba-47a5-854d-e6b53101adb7",
            "sampleSheetName": "SampleSheet.V2.134567.csv",
            "apiUrl": "https://api.aps2.sh.basespace.illumina.com/v2/runs/r.4Wz-ABCDEFGHIJKLM-A",
            "name": "222222_A01052_1234_BHVJJJJJJ",
            "id": "r.4Wz-ABCDEFGHIJKLMN-A",
            "instrumentRunId": "222222_A01052_1234_BHVJJJJJJ",
            "status": "PendingAnalysis"
            }
        }
    }
```
And emit 'SequenceRunStateChange' event
```
{
    "version": "0",
    "id": "abcdefgh-111-aaaa-e980-1a8d6dab96d1",
    "detail-type": "SequenceRunStateChange",
    "source": "orcabus.sequencerunmanager",
    "account": "44444444",
    "time": "2024-12-03T23:07:09Z",
    "region": "ap-southeast-2",
    "resources": [],
    "detail": {
        "id": 34,
        "instrumentRunId": "222222_A01052_1234_BHVJJJJJJ",
        "runVolumeName": "bssh.123456789fabcdefghijkl",
        "runFolderPath": "",
        "runDataUri": "gds://bssh.123456789fabcdefghijkl",
        "sampleSheetName": "SampleSheet.V2.134567.csv",
        "startTime": "2024-11-08T00:10:13.0962060Z",
        "status": "STARTED"
    }
}
```

### CODE REVIEW

**Comment by raylrui** [comment]
@reisingerf 
for gdsFolderPath in the CAv2 ENS subscription, it always empty like`"gdsFolderPath": ""`
does that means runFolderPath in 'root path', or do we need organise a new one like icav1 `"runFolderPath": "/Runs/5555555_A01001_0193_BBBBBBDRX5_r.88888888ASU26EYuyeJHew"`?
I didn't find any BSSH api for that folder path

**Comment by reisingerf** [comment]
FYI @victorskl

**Comment by raylrui** [comment]
just for refer, example event in dev `s3://orcabus-universal-events-archive-843407916570/events/year=2024/month=12/day=04/` , [link](https://ap-southeast-2.console.aws.amazon.com/s3/buckets/orcabus-universal-events-archive-843407916570?bucketType=general&prefix=events%2Fyear%3D2024%2Fmonth%3D12%2Fday%3D04%2F&region=ap-southeast-2&showversions=false#)

**Comment by reisingerf** [comment]
Yes, the new event does not have all the same information we could find in the ICAv1 events.

The new event will contain an API link though were this information can be retrieved from: `apiUrl`
(that needs separate credentials IIRC so maybe leave for a later time)

I am not sure we need this information right now. The important information for now is: run id, sample sheet name, status and timestamp. 

Perhaps we use the value of `apiUrl` for the `runDataUri` or add the `apiUrl` as a new field? @victorskl opinions?

**Comment by reisingerf** [comment]
At some point I do want to pull in the SampleSheet and related information, but that can wait. 
Priority for now is to capture the events, so the UI can report the status (and the lab can comment on it once the support for comments is in).

**Comment by raylrui** [comment]
yes, it is okay for now, and work fine to insert/update record to database for UI, 

just a bit concern about [bs-runs-upload-manager](https://github.com/umccr/orcabus/tree/main/lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/constructs/bs-runs-upload-manager)
 with [event rule](https://github.com/umccr/orcabus/blob/ed949c5280db406688242a5ee8b64d03b37f8c01/lib/workload/stateless/stacks/bs-runs-upload-manager/deploy/constructs/bs-runs-upload-manager/index.ts#L122C1-L132C8) to consume the SUCCEEDED 'SequenceRunStateChange' event, but we can check it later to see 

comment function will be added through https://github.com/umccr/orcabus/pull/748
will merge it later after this one, and with UI refactor

**Comment by victorskl** [comment]
Yup. Ray, if we haven't captured yet then pls add these 3 fields be captured, pls. These fields become crucial to retrieve further details about each sequencing run.

```
"v1pre3Id": "444555555555",
"icaProjectId": "12345678-53ba-47a5-854d-e6b53101adb7",
"apiUrl": "https://api.aps2.sh.basespace.illumina.com/v2/runs/r.4Wz-ABCDEFGHIJKLM-A",
```

We no longer have direct access to underlay GDS anymore. But through these ^^ 3 fields info; hence they are now replaced GDS details - and, we get blank out as such.
```
"gdsFolderPath": "",
"gdsVolumeName": "bssh.123456789fabcdefghijkl",
```

**Comment by raylrui** [comment]
Close as https://github.com/umccr/orcabus/pull/753 has include all changes

**Pull request closed without merging**
