### PR TITLE
Support s3 uris and bump wrapica to 2.27.1

### PR DESCRIPTION
**Pull request by alexiswl**
## TODO
- [x] Determine if development service user can access underlying storage configurations

### CODE REVIEW

**Comment by victorskl** [comment]
Checking on this...

**Review by victorskl — APPROVED** [review]
Okay, so far looking good. Tick the box, just in case, you'd like to push it through.

**Comment by alexiswl** [comment]
This is working now @reisingerf has shared the dev-cache credentials

**Comment by alexiswl** [comment]
Superseded by #451, forgot I hadn't merged this

**Pull request closed without merging**
