### PR TITLE
feat(filemanager): add `FileStateChange` event schema

### PR DESCRIPTION
**Pull request by mmalenic**
Related to #605, addresses point 1 of https://github.com/umccr/orcabus/issues/605#issuecomment-2418388645.

### Changes
* Adds the `FileStateChange` schema which will support tagging objects to transition them to another storage class, or delete them.
    * I don't think I've missed anything, as both expiring and transitioning objects is supported.
    * I haven't added any support for `NoncurrentVersionTransition`, `NoncurrentVersionExpiration`, `AbortIncompleteMultipartUpload`, or `ExpiredObjectDeleteMarker`, because I feel like these would be covered by bucket-wide rules that apply to all objects? It doesn't seem like it would be useful to have these apply differently based on the object prefix. I'm happy to add it in if we think it's useful though?
* The implementation uses a build command to generate the schema from Rust code. This is more convenient because the same code can be used to parse incoming events.

### CODE REVIEW

**Review by brainstorm — APPROVED** [review]

**Comment by reisingerf** [comment]
Hm, not sure I understood the intention correctly... 

The schema defines a **FILE** state change event, but it does not really link it to any particular file. It rather feels like a policy or lifecycle transition rule change. 

It also does not seem to have provisioning for other "state" changes, like "archived" or "deleted" or "moved" .... 

The "source" in the examples is `orcabus.filemanager` indicating an announcement from the FM?

Also, not sure all the S3 lifecycle details are needed/useful. We can't create rules for each and every file/event...

**Comment by mmalenic** [comment]
Yes, I think this probably isn't a `StateChange` kind of event, it more a transition event.

> It also does not seem to have provisioning for other "state" changes, like "archived" or "deleted" or "moved" ....

On this note, one thing the filemanager could do that isn't possible using s3 lifecycles is to move objects between locations. E.g. a workflow run could say to move the objects to an archive bucket after n-days. Not sure if something like this would be useful.

**Comment by victorskl** [comment]
@reisingerf @mmalenic Let us quick catch up call next week on this, pls. I'll follow up ping you on next Monday.

**Comment by mmalenic** [comment]
Putting this feature on hold for now, as we need to figure out if using events/tags is the best approach for this.

**Pull request closed without merging**
