### PR TITLE
Feat(MM): Additional MM Endpoint and Library Filter

### LINKED ISSUE #575: metadata-manager: Cleanup Dangling Record
The auto-sync/loader may delete libraries record if no longer exists for that particular year (as described in [how-syncing-the-data-works](https://github.com/umccr/orcabus/tree/main/lib/workload/stateless/stacks/metadata-manager#how-syncing-the-data-works) readme). We should have a way perhaps a lambda to identify and clean records that don't have a link to a library.

### LINKED ISSUE #578: Show error message in payload for icav2 workflows that fail
A bit of hacking required for cttso v2 runs (that have succeeded) but for general ICAv2 runs that have failed, we should be able to grab the 'error' message attribute from the ICAv2 event

### PR DESCRIPTION
**Pull request by williamputraintan**
- Add Deletion and Patch endpoint for each metadata model (JWT email token will track the user)
- Add `is_library_none` filter to Sample and Subject model to find the library-less entity

Resolve #575

### CODE REVIEW

**Review by victorskl — APPROVED** [review]
LGTM

**Review by reisingerf — APPROVED** [review]

**Comment by reisingerf** [comment]
The idea is to guard those endpoints with Verified Permissions?

**Comment by williamputraintan** [comment]
> The idea is to guard those endpoints with Verified Permissions?

Yes, currently is using the same Amazon Verified Permission (AVP) which currently only has admin/no-admin. I suppose we would only need to add new policy at the AVP for these endpoints for more complex auth.

**Comment by reisingerf** [comment]
Yup, all good!
As long as we can prevent uncontrolled access it's fine for now. 
We'll get more detailed use cases for the new policies soon enough ;-)

**Comment by victorskl** [comment]
Very soon...

**Comment by victorskl** [comment]
Btw, just for my understanding/context - may be you might have discussion with @alexiswl on this.

So, the issue #578 reported by Alexis related to (fixed by) this enhancement at MM, correct?

**Comment by williamputraintan** [comment]
> Btw, just for my understanding/context - may be you might have discussion with @alexiswl on this.
> 
> So, the issue #578 reported by Alexis related to (fixed by) this enhancement at MM, correct?

Sorry, I link the wrong issue. It was supposed to be #575

**Pull request merged**
