### PR TITLE
Feat (metadata-manager): Update model

### PR DESCRIPTION
**Pull request by williamputraintan**
Update the model to support more data ingestion from the tracking sheet.

| Sheet Header      | Table        | Field Name         |
|-------------------|--------------|--------------------|
| SubjectID         | `Individual` | individual_id      |
| ExternalSubjectID | `Subject`    | subject_id         |
| SampleID          | `Sample`     | sample_id          |
| ExternalSampleID  | `Sample`     | external_sample_id |
| Source            | `Sample`     | source             |
| LibraryID         | `Library`    | library_id         |
| Phenotype         | `Library`    | phenotype          |
| Workflow          | `Library`    | workflow           |
| Quality           | `Library`    | quality            |
| Type              | `Library`    | type               |
| Coverage (X)      | `Library`    | coverage           |
| Assay             | `Library`    | assay              |
| ProjectName       | `Project`    | project_id         |
| ProjectOwner      | `Contact`    | contact_id         |

### CODE REVIEW

**Review by reisingerf — APPROVED** [review]
Let's go!

**Comment by alexiswl** [comment]
LGTM!

**Review by victorskl — APPROVED** [review]
Alright. Let's do this!

**Comment by victorskl** [comment]
[Assign internal SBJ identifier via external service](https://trello.com/c/2i6PvmjT/690-assign-internal-sbj-identifier-via-external-service)

**Pull request merged**
