### PR TITLE
Feature/bclconvert interop qc manager (and refactor icav2 configuration)

### PR DESCRIPTION
**Pull request by alexiswl**
# BCLConvert Interop QC CWL pipeline

## TODO 

- [x] Wait for https://github.com/umccr-illumina/ica_v2/issues/180 to test if this pipeline actually works
- [x] Add eventFilter and subscribe to orcabus internal events (such as workflow manager)
- [x] Add eventFilter and subscribe to external events (such as ICAv2 pipeline state change)
- [x] Fix putEvents at the end of each of the step functions to fire at the actual orcabus event pipe - state machine's permissions might need to be adjusted for this to actually work
- [x] Integrate into orcabus codepipeline for deployment
- [ ] Reorg payloads such that all payload items are under the 'data' section, except for 'refId' and 'version'
- [ ] Reorg workflow run statechange inputs so that workflowType is now workflowName, source is longhand version of source name
- [ ] Work with #305 to determine harmonious event communication between systems

## Readmes 

To view the Readmes related to this PR

* [BCLConvert InterOp QC Stack](https://github.com/umccr/orcabus/tree/feature/bclconvert-interop-qc-manager/lib/workload/stateless/stacks/bclconvert-interop-qc-pipeline-manager)
* [ctTSOv2 Stack](https://github.com/umccr/orcabus/tree/feature/bclconvert-interop-qc-manager/lib/workload/stateless/stacks/cttso-v2-pipeline-manager)

* [ICAv2 Handle WFM Ready Event Construct](https://github.com/umccr/orcabus/tree/feature/bclconvert-interop-qc-manager/lib/workload/components/dynamodb-icav2-ready-event-handler-sfn)
* [ICAv2 Handle Event State Change SFN Construct](https://github.com/umccr/orcabus/tree/feature/bclconvert-interop-qc-manager/lib/workload/components/dynamodb-icav2-handle-event-change-sfn)

### CODE REVIEW

**Comment by alexiswl** [comment]
@victorskl @reisingerf please have a look through the readmes above

**Comment by victorskl** [comment]
.. will read them through today

**Comment by victorskl** [comment]
Went through the READMEs, LGTM. Massive effort! 
..will review this PR once you mark it ready.

**Comment by alexiswl** [comment]
> ..will review this PR once you mark it ready.

Yes ready to go!

**Review by victorskl — APPROVED** [review]
Again, massive effort, kudos.! 👍

**Review by reisingerf — APPROVED** [review]
Awesome write-up! 
Thanks!

**Comment by alexiswl** [comment]
Sorry, to make things difficult, @williamputraintan should I merge #293 into this branch first? That's where the cttso v2 stack in dev is currently at anyway

**Comment by alexiswl** [comment]
Forging ahead, merging #295 into here

**Comment by victorskl** [comment]
I checked up, all good.

**Comment by alexiswl** [comment]
I've merged this into my glue stack. Once I can get it 'end-to-end' solution I will push into smaller PRs.

**Comment by alexiswl** [comment]
Superseded by https://github.com/umccr/orcabus/pull/337

**Pull request closed without merging**
