### PR TITLE
Project setup refactor

### PR DESCRIPTION
**Pull request by victorskl**
* Made the repo root is just the CDK TypeScript project
* Refactored nested Makefile for how to call and run each
  toolchain app dependencies installation and test suite
* Refactored Docker compose stack into each app inner dir
  app root and, made shared dir for common compose stack
* Made GitHub Action PR Build to `make check` as pre-flight
  checkpoint before running main CI/CD automation CodePipeline
* Offered common system-wide tools as Brewfile and allowed
  dev to choose any method fit to suit to set up local dev
* Improved README.md and MICROSERVICE.md to reflect changes

Python
* Refactored Python requirements and Django setup into its
  own inner directory. Developer should not need to set up
  Python if they are not needed to
* Refactored Django app to use PostgreSQL
* Refactored Django app structure

### CODE REVIEW

**Comment by victorskl** [comment]
@reisingerf (I know you are away) and, @alexiswl @pdiakumis pls review too if you are able... This was based on long discussion during devops meeting some weeks ago..!

**Comment by victorskl** [comment]
[OrcaBus V1: Setup test framework for runtime and deployment CDK Constructs](https://trello.com/c/4b8Nmgrb/1444-orcabus-v1-setup-test-framework-for-runtime-and-deployment-cdk-constructs)

**Comment by andrewpatto** [comment]
No major red flags from me.. seems like a good idea to get this merged and people using it asap - and then iterate from there

**Comment by williamputraintan** [comment]
Merging

**Pull request merged**
