### PR TITLE
Fix/workflowrun state handling

### PR DESCRIPTION
**Pull request by reisingerf**
FYI: @alexiswl 

This should fix the WRSC handling of linked libraries, etc....

### CODE REVIEW

**Review by victorskl — APPROVED** [review]
Nice refactor.!

**Comment by alexiswl** [comment]
Ah I should move all of my statuses to uppercases then

**Comment by alexiswl** [comment]
Should non-wrsc statuses also change to upper case? 

i.e should `SubjectInSamplesheet` become `SUBJECT_IN_SAMPLESHEET`?

**Comment by reisingerf** [comment]
I think it would be good to follow some sort of convention, yes.

For now the workflow manager changes everything to upper case and replace "-" to "_".

But in your case, these are not WRSC statuses, but events internal to the stacky logic, no?

**Comment by alexiswl** [comment]
> But in your case, these are not WRSC statuses, but events internal to the stacky logic, no?

Yes these are internal events not going through the workflow manager

**Pull request merged**
