### PR TITLE
fix(filemanager): make `HeadObject` optional

### LINKED ISSUE #354: filemanager: `HeadObject` causes error when there are no permissions
The filemanager attempts to grab the `HeadObject` of ingested events in order to update fields like `last_modified`, `storage_class`, `checksum`, etc. If this fails due to a lack of permissions on the bucket, then ingestion fails. Instead, the filemanager should ingest the event even if `HeadObject` fails, as these fields are optional anyway.

### PR DESCRIPTION
**Pull request by mmalenic**
Closes #354 

### Changes
* Makes the `HeadObject` call for ingesting events optional.

### CODE REVIEW

**Review by brainstorm — APPROVED** [review]

**Comment by brainstorm** [comment]
Ah, good consistency catch... so we now ignore but log because nothing else can be done I guess 👍

**Comment by mmalenic** [comment]
### Update
* Also added permissions for the ingest Lambda function to access pipeline cache buckets

**Review by victorskl — APPROVED** [review]
LGTM.

Just heads up. Conceptually, `HeadObject` ops can determine the object status details once it get moved into Glacier Deep Archive tier or, objects from archival bucket.

**Review by reisingerf — APPROVED** [review]

**Comment by mmalenic** [comment]
### Another update

* I've added a `NamedLamdbaRole` construct to support creating named roles.
* Add warning for a lack of permissions.
* Fixed CDK nag.

**Pull request merged**
