### PR TITLE
Oncoanalyser / Sash stack and glue services

### PR DESCRIPTION
**Pull request by alexiswl**
~~ Tests currently failing due to cdk-nag on AWS Step Functions~~

## TODO

- [x] Apply https://github.com/umccr/infrastructure/pull/485 to development account
- [x] Test oncoanalyser SFN both successfully submitting job and retrieving batch events (and then spitting them out again as workflow run statechange events)
- [x] Test sash SFN both successfully submitting job and retrieving batch events (and then spitting them out again as workflow run statechange events)

## Related PRs

* https://github.com/umccr/infrastructure/pull/485
* https://github.com/umccr/nextflow-stack/pull/115

### CODE REVIEW

**Review by victorskl — APPROVED** [review]

**Comment by victorskl** [comment]
Related https://github.com/umccr/nextflow-stack/pull/115

**Review by reisingerf — APPROVED** [review]

**Comment by reisingerf** [comment]
Yup, happy to suppress cdk-nag.

**Review by scwatts — APPROVED** [review]
Thanks for the reviewer request, assuming just for visibility - I don't have much context wrt OrcaBus for these changes!

**Comment by victorskl** [comment]
🥁

**Pull request merged**
