### PR TITLE
Improved sequence_run_manager API Gateway setup

### PR DESCRIPTION
**Pull request by victorskl**
Related #139

### CODE REVIEW

**Comment by victorskl** [comment]
FYI stuff about API Gateway in the PR @mmalenic @alexiswl

**Comment by victorskl** [comment]
Related #174

**Comment by victorskl** [comment]
Related #176

**Review by reisingerf — APPROVED** [review]

**Comment by victorskl** [comment]
@williamputraintan PR pls

**Review by williamputraintan — APPROVED** [review]

**Comment by victorskl** [comment]
Merging...

**Pull request merged**
