### PR TITLE
Implemented Sequence Run Manager BSSH event processing

### PR DESCRIPTION
**Pull request by victorskl**
* We will be still subscribing to ICA v1 ENS for BSSH event
* Our internal entity model as well as domain model are not specific to BSSH
* SequenceDomain struct wrap Sequence entity instance and its purpose is to
  handle all translation between entity to domain event schema semantic
* EventBus schema auto-generated Code Bindings `sequencerunstatechange` is part
  of domain package. Its internals should be interfaced through SequenceDomain
* Made a good unit test coverage on marshall/unmarshall and all aspect of serde
* Made `DJANGO_SETTINGS_MODULE` config mandatory instead of defaulting to base
* Added documentation

### CODE REVIEW

**Comment by victorskl** [comment]
[OrcaBus V1: Implement SequenceRunManager microservice app](https://trello.com/c/TQX8yJuc/1445-orcabus-v1-implement-sequencerunmanager-microservice-app)

**Comment by victorskl** [comment]
[ICA V2 Migration: BSSH sequencing event to ICAv2 notification](https://trello.com/c/eRYktdZp/1489-ica-v2-migration-bssh-sequencing-event-to-icav2-notification)

**Review by brainstorm — APPROVED** [review]

**Review by reisingerf — APPROVED** [review]
Awesome!

**Review by williamputraintan — APPROVED** [review]

**Comment by victorskl** [comment]
Thanks all, merging...

**Pull request merged**
