### PR TITLE
Fixed ctTSOv2 workflowVersion to 2.5.0

### PR DESCRIPTION
**Pull request by victorskl**

### CODE REVIEW

**Comment by victorskl** [comment]
Not so confident about this. But, pls have a look, Alexis.

**Comment by alexiswl** [comment]
Ah good spot!

**Comment by victorskl** [comment]
Hold on, I found this is static config inside `constants.ts` 
Let me double check.

**Comment by victorskl** [comment]
Ok, guess, I will leave it with you for later refactor/realign these config parameter with cttsov2-pipeline-manager stack which leverage these config param from `constants.ts`.

For now, this fix follow as the way it is...

**Comment by victorskl** [comment]
How about this PR @alexiswl? If you have another plan, happy to on-hold or abandon, etc..

**Review by alexiswl — APPROVED** [review]
Hmm, yes using contants.ts would be good but also happy to wait and then whatever replaces stacky can use the constants.ts and we just hardcode for now

**Comment by victorskl** [comment]
Sound good. I will keep an eye on this, too. Part of stacky backlog...

**Pull request merged**
