### PR TITLE
Bug fixes for 0.2.1

### PR DESCRIPTION
**Pull request by alexiswl**
Handle project copy batch:
  * After 'successful' copy, check file sizes are the same between source and destination  #572

Fix cttsov2 outputs json:
  * Error when collecting error message, just a typo #571

Roll back library_set init
  * Was put in to prevent sfn failure when a sample type was not present on a run but now fails due to dynamodb not supporting empty sets, will find a better solution soon  #570

### CODE REVIEW

**Comment by alexiswl** [comment]
Deploying to dev atm, will kick off one cttso sample first to ensure that 571 and 572 fixes are working properly.

**Comment by alexiswl** [comment]
@victorskl this one is good to go

**Comment by victorskl** [comment]
Sure, will work on patching to prod.

**Review by victorskl — APPROVED** [review]
LGTM

**Comment by victorskl** [comment]
Merging.. I will cherry pick them.

**Pull request merged**
