### PR TITLE
Updated SequenceRunStateChange schema

### PR DESCRIPTION
**Pull request by victorskl**
* Refactored service namespace: `srm` to `sequencerunmanager`
* Status value case change request: e.g. `succeeded` to `SUCCEEDED`

### CODE REVIEW

**Comment by victorskl** [comment]
- [ ] Waiting on PR #308 merge first

**Comment by victorskl** [comment]
This change request is based on meeting notes 16/05/2024 - https://umccr.slack.com/archives/C03ABJTSN7J/p1715906599365689

**Comment by victorskl** [comment]
Related #307

**Review by reisingerf — APPROVED** [review]

**Comment by victorskl** [comment]
Merging for now. Pls comment if any, Alexis.

**Pull request merged**
