### PR TITLE
Add Events system to bssh fastq copy manager (and deprecate icav2 copy batch utility stack)

### PR DESCRIPTION
**Pull request by alexiswl**
Refactor bssh and cttso v2 so each service generates its own icav2 copy file service, rather than use a standalone copy batch utility.  

ICAv2 file copy construct has both single and batch constructs so cttsov2 can use single (since it's only using one dest uri).  

See https://github.com/umccr/orcabus/issues/293 for more info

## TODO 

> ~~This branch is forked from the PR below so this needs to be merged first~~
- [ ] ~~PR #192 Instead we merge into #192~~

### CODE REVIEW

**Comment by alexiswl** [comment]
@williamputraintan if I delete a service from the stack will it actually delete? I guess we will find out soon

**Comment by alexiswl** [comment]
Also I will deal with secrets detected by GitGuardian

**Comment by williamputraintan** [comment]
> @williamputraintan if I delete a service from the stack will it actually delete? I guess we will find out soon

I don't think so, might need to `yarn cdk-stateless destroy ...` manually

**Comment by alexiswl** [comment]
> I don't think so, might need to yarn cdk-stateless destroy ... manually

Cool, will wait until this is merged before doing that then, incase there is actually a service in prod using it

**Pull request merged**
