### PR TITLE
Fix ica event pipe name

### PR DESCRIPTION
**Pull request by raylrui**
Fix the ica event pipe name with the fixed pipe name.

So in the event rules pattern, we can use `"source": "Pipe IcaEventPipeStackPipe",` rather than aws assigned id ` "source": "Pipe IcaEventPipeConstru-aVEAl34nl7zf",`

### CODE REVIEW

**Comment by reisingerf** [comment]
@williamputraintan @victorskl 
FYI: I guess we'll be running into those kind of issues... and so far there are a couple of options I could see as a solution, please add if you have others:

We don't want direct stack dependencies, so need a different way to allow entity resolution. 

Fixing entity names in the shared config is one option, but may come with limitations on deployability (e.g. creating unique independent entities). Slightly better may be to use name prefixes (with autogenerated suffix) to ensure unique names, but that may create issues with the discovery process (lookup using wildcards or filtering if more than one resource).

I guess a better option would be to register resources that are shared into a discovery service (like CloudMap) so they are available to consumers within the correct context.

I think for now I am OK with fixing that name.

**Comment by victorskl** [comment]
Okie. So, this is pinning the named resource so that there shouldn't be two instances of the same should exist, correct?

**Comment by victorskl** [comment]
> discovery service (like CloudMap) 

See another case #265

**Comment by reisingerf** [comment]
Yes, it has popped up before... 
CloudMap could be a good option, but until we have explored and instrumented that a bit more I am happy with fixing the names

**Comment by raylrui** [comment]
Thanks for your comment.
My first thought about this is just put the `props.icaEventPipeName` in the new pipe resource, so the event pipe we create here has name define as in the props, like this
```
new pipes.Pipe(this, "Pipe", {
      pipeName: props.icaEventPipeName,
      source: new SqsSource(this.icaQueue),
      target: new EventBusTarget(this.mainBus, {
        inputTransformation: targetInputTransformation,
      }),
```
And then, in my translator service, I can use the eventPattern with define pipe source like this 😅:
```
const rule = new Rule(this, 'Rule', {
      eventBus: this.mainBus,
      eventPattern: {
        account: [Stack.of(this).account],
        detailType: ['Event from aws:sqs'],
        source: [`Pipe ${props.IcaEventPipeName}Pipe`],
        detail: {
          'ica-event': ['*'],
        },
      },
    });
```
I am not sure if it bring too much here. But sure, CloudMap will be the great option to map all service rather than define fix names in our constants.

**Comment by victorskl** [comment]
That's ok. Good discussion. Early days. Let us keep moving. This is fine. We can flex this, if need be.

**Comment by victorskl** [comment]
Btw, event `source` naming follows reverse domain naming pattern. Like Java package naming.

```
orcabus.<service1>
orcabus.<service2>
orcabus.<service3>
```

Not sure; it is viable to maintain this pattern here. If we can, perhaps `orcabus.icapipe` might be good candidate...

**Comment by raylrui** [comment]
>Not sure; it is viable to maintain this pattern here. If we can, perhaps orcabus.icapipe might be good candidate...

As I research, AWS Pipes handles transformations, especially for critical fields like `source` and `detail-type` in EventBridge events. These fields are core attributes of the event itself, managed at a higher level than the `detail` payload, which is what is typically manipulated by transformations in AWS Pipes. 
So AWS Pipes **doesn't directly allow overriding the source and detail-type at the Pipe level** because these are set by the AWS Pipes framework itself when routing events through Pipes.

**Comment by raylrui** [comment]
Hi @reisingerf @victorskl  I will drop the PR for now, as I have coupled the translator service within the ica event pipe stack in another PR, see #204.
For the name convention, we may have more PRs in the future.

**Pull request closed without merging**
