### PR TITLE
Revert "Remove cdk.out assets to prevent synth output"

### PR DESCRIPTION
**Pull request by alexiswl**
This reverts commit 2d20a9df850d44cfac90274aa2f1091ad2edb39f.

### CODE REVIEW

**Comment by alexiswl** [comment]
@williamputraintan did you want to give this a test run?

**Comment by alexiswl** [comment]
Ah wait, I see that's happened, FileManagerStack now fails

**Comment by williamputraintan** [comment]
Yes, did run this manually. But now fails on different part, will investigate on it.

**Comment by williamputraintan** [comment]
Will try let the pipeline handle the build instead of manual deployment.

**Pull request merged**
