### PR TITLE
Refactor glue constructs

### PR DESCRIPTION
**Pull request by alexiswl**
Out with the Scotch, Selleys and Super

In with the clag, elmer, gorilla and jb-weld (kwik and loctite still WIP).  

cttsov2 (and wgts + TN in future) will subscribe to the event showers in 'clag'.  

Much of these glue databases will mock the 'policy manager' while that is still WIP.  

Aim to get this running with wgts, and TN (and maybe WTS) by the end of next week

- [x] Test out the wgts alignment qc post fastq list row qc service events
- [x] Build the tn glue service and tn deployment service
- [x] Build the  wts glue service and the wts deployment service

### CODE REVIEW

**Comment by victorskl** [comment]
@alexiswl Do you reckon, shall I start review this..

**Comment by alexiswl** [comment]
Yes please go for it! Has a successful tumor normal run so everything is almost good for go. Just testing latest changes on cram files and will release latest versions of CWL workflows to be compatible with ICAv2. 

But that's independent of this PR

**Comment by victorskl** [comment]
Understood. Sound good. Let do it.!

**Comment by victorskl** [comment]
Reviewing...

**Review by victorskl — APPROVED** [review]
Epic.!

**Pull request merged**
