### PR TITLE
Updated SequenceRunManager service to align with SequenceRunStateChange

### LINKED ISSUE #276: Follow up for SequenceRunStateChange schema changes
**Context:**

We have finalised the schema setup #257 and, the `SequenceRunStateChange` schema is now published in OrcaBus Schema Registry.

There has been changes with `SequenceRunStateChange` on trim some optional attributes and, more importantly adopting to `camelCase` on properties. See #266 PR for details.

**Change Requests:**

This affected 2 services: `SequenceRunManager` (upstream) and `BsRunsUploadManager` (downstream)

**Actions:** 

- Follow up with the schema changes for these 2 services

### PR DESCRIPTION
**Pull request by victorskl**
* Updated SequenceRunStateChange schema code binding from Schema Registry
* Added djangorestframework-camel-case to automate snake_case to camelCase

Resolves #276

### CODE REVIEW

**Comment by victorskl** [comment]
I have made "split-join" PR technique for easier review with base feature branch changes and, other supplementary changes with auxiliary feature branches that I would wish to go together with CI/CD. 

This optimises 2 aspects: PR review and CI/CD build time. Not new; we already did elsewhere.

- [ ] #278

**Comment by victorskl** [comment]
After this PR merged, team is pretty much ready for the very first part of automation i.e. auto kick off basespace bcl_convert over to ICAv2, routinely with every other weekly sequencing. We can pilot run that in upcoming weeks...

FYI @ohofmann

**Review by reisingerf — APPROVED** [review]

**Review by williamputraintan — APPROVED** [review]

**Comment by victorskl** [comment]
I will wait current CI build clear away first.

**Comment by victorskl** [comment]
I will be merging first... Need this to be in to main.

**Pull request merged**
